### ISSUE TITLE
Find out why some game objects do not collide

### ISSUE THREAD

**Issue by Humblean** [Herkulisch/Chip-8#2]
Some objects in the games just do not collide, they just phase through each other, I have to find out if these are bugs from the rom itself, or if some of my instructions are not working properly. If the second one is the case, I suspect the DRW methods and generally the display stuff to be the issue.

**Comment by tobiasvl** [comment]
I'm not sure I understand the code here: https://github.com/Herkulisch/Chip-8/blob/master/src/chip/instruction.rs#L306-L310

I'm not a Rust expert, but isn't `chip.display.pixel(sp_x as u8, sp_y as u8)` wrong? Aren't you using the current sprite coordinates (ie. X is between 0 and 8, and Y is between 0 and N somewhere) as display coordinates? In other words, it looks like you're always checking the upper left corner of the display for collisions, rather than the actual location of the sprite. I would think you should use `dis_x` and `dis_y` instead.

If this is the bug, it looks like it's present on lines 306 and 309.

Also on line 309, I think there might be another issue: You seem to set the collision flag if the display pixel changed from the previous value after drawing the sprite. This is incorrect; the collision flag should only be set if drawing the sprite turned a pixel from on to off.

**Comment by Humblean** [comment]
Hey Tobias, thanks a lot. I never thought that anyone except me would watch at this 😂. But you did and I'm happy about that. I have some exams to take right now, but I will happily have a look at this right after them. Thanks for reading through my code, I hope it was not too bad. 😂
And the thinks you said make a lot of sense, I guess I got confused cause I have to many variables with the word display included. 
Have a nice day 😄

**Comment by Humblean** [comment]
I was too excited, so I implemented both your recommentations right away and it seems like they work. Thanks a lot 😄

I still have some visual glitches on some ROMs (ghostEscape in this example), but I think they have nothing to do with the collision logic. Don't feel forced to fix this issue too. I just make this issues as some sort of diary. So they help me remember where I stopped last time.


![grafik](https://user-images.githubusercontent.com/55994229/134824780-de08733e-c809-4f4a-aa6c-6746564aa8f9.png)
